# Build stage
FROM node:18 AS build
WORKDIR /app
COPY ./frontend/client/package*.json ./
RUN npm install
COPY ./frontend/client .
RUN npm run build

# Serve stage
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
